//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class LightBlock : Block
	{
		void Start(){
			this.Duration = 3f;
			this.Image = new Sprite ();
		}
		
		void Update(){
			this.Duration -= Time.deltaTime;
			this.Special ();
			if (this.Duration < 0) {
				Destroy();
			}
		}

		//this block attracts enemies
		void Special(){
			return;
		}
	}
}

