//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class StoneBlock : Block
{
		void Start(){
			this.Duration = 5f;
			this.Image = new Sprite ();
		}

		void Update(){
			this.Duration -= Time.deltaTime;
			if (this.Duration < 0) {
				Destroy();
			}
		}
		
		void Special(){
			return;
		}
}

